---
- name: Create nginx dirs
  ansible.builtin.file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    recurse: true
  with_items:
    - "{{ nginx_opt_dir }}"
    - "{{ nginx_log_dir }}"
    - "{{ nginx_opt_dir }}/error-page"
    - "{{ nginx_opt_dir }}/site.d"
    - "{{ nginx_opt_dir }}/sites-enabled"
    - "{{ nginx_opt_dir }}/ssl"


- name: Transfer site.d configuration
  ansible.builtin.template:
    mode: "0644"
    src: "{{ item }}"
    dest: "{{ nginx_opt_dir }}/site.d/{{ item | basename }}"
  with_fileglob:
    - ../templates/config/site.d/*.*

- name: Transfer error-page configuration
  ansible.builtin.template:
    mode: "0644"
    src: "{{ item }}"
    dest: "{{ nginx_opt_dir }}/error-page/{{ item | basename }}"
  with_fileglob:
    - ../templates/config/error-page/*.*

- name: Transfer nginx.conf configuration
  ansible.builtin.template:
    mode: "0644"
    src: "{{ item }}"
    dest: "{{ nginx_opt_dir }}/nginx.conf"
  with_fileglob:
    - ../templates/config/nginx.conf

- name: Transfer sites-enabled configuration
  ansible.builtin.template:
    mode: "0644"
    src: "{{ item }}"
    dest: "{{ nginx_opt_dir }}/sites-enabled/{{ item | basename }}"
  with_fileglob:
    - ../templates/config/sites-enabled/*.*

- name: Create nginx logs files
  changed_when: false
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 0644
    state: touch
  with_items:
    - "{{ nginx_log_dir }}/error.log"
    - "{{ nginx_log_dir }}/access.log"
