---

- name: Copy nginx script
  ansible.builtin.template:
    src: "nginx"
    dest: /usr/local/bin/nginx
    mode: 0755
    owner: root
    group: root

- name: Copy nginx service
  ansible.builtin.template:
    src: "nginx.service"
    dest: /etc/systemd/system/nginx.service
    mode: 0644
    owner: root
    group: root
  notify:
    - restart nginx

- name: Ensure nginx service is restarted
  ansible.builtin.service:
    name: Nginx
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for nginx to become ready
  ansible.builtin.wait_for:
    host: "0.0.0.0"
    port: "80"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
