#!/usr/bin/env bash

set -eux -o pipefail

# pull the image before so we dont first remove the container and then pull
docker pull nginx:"{{ nginx_version }}"

docker rm -f -v nginx || :

docker run -u root --net=host --rm --name=nginx \
	-v {{ nginx_opt_dir }}/sites-enabled:/etc/nginx/sites-enabled:rw \
	-v {{ nginx_opt_dir }}/nginx.conf:/etc/nginx/nginx.conf:rw \
	-v {{ nginx_opt_dir }}/ssl:/etc/nginx/ssl:rw \
	-v /var/www:/var/www:rw \
	-v /var/log/nginx:/var/log/nginx:rw \
    nginx:"{{ nginx_version }}"
